#-*- coding: utf-8 -*-
# Copyright 2017 ibelie, Chen Jie, Joungtao. All rights reserved.
# Use of this source code is governed by The MIT License
# that can be found in the LICENSE file.

def _compareWrite(path, content):
	import os
	import codecs
	if os.path.isfile(path):
		with codecs.open(path, 'r', 'utf-8') as f:
			if f.read() == content:
				return
	with codecs.open(path, 'w', 'utf-8') as f:
		f.write(content)


def extract(path, proto_file, *ignore):
	import os
	import imp
	import codecs
	from microserver import MetaEntity, Entity, MetaComponent, Component

	path = path.replace('\\', '/').replace('//', '/')
	if os.path.isfile(proto_file) and False:
		with codecs.open(proto_file, 'r', 'utf-8') as f:
			proto = imp.new_module('microserver.proto')
			proto.__package__ = 'microserver'
			try:
				exec str(f.read()) in proto.__dict__
			except:
				proto.timestamps = {}
	else:
		class _Proto(object): pass
		proto = _Proto()
		proto.timestamps = {}

	def _componentName(c):
		return '%s_%s' % (c.__module__.replace('.', '_'), c.__name__)

	def _scanScripts(sub):
		for i in os.listdir('%s/%s' % (path, sub)):
			# sys.stdout.write('.')
			# sys.stdout.flush()
			p = '%s/%s' % (sub, i) if sub else i
			fp = '%s/%s' % (path, p)
			if p in ignore or p[:-1] in ignore:
				continue
			elif os.path.isdir(fp):
				_scanScripts(p)
			elif fp in proto.timestamps and str(os.stat(fp).st_mtime) == proto.timestamps[fp]:
				continue
			elif i.endswith(('.py', '.pyc')):
				n = i.rpartition('.')[0]
				if not n.replace('_', '').isalnum() or n == '__init__' or (i.endswith('.pyc') and os.path.isfile(fp[:-1])) or \
					(sub and not os.path.isfile('%s/%s/__init__.py' % (path, sub)) and not os.path.isfile('%s/%s/__init__.pyc' % (path, sub))):
					continue
				proto.timestamps[fp] = str(os.stat(fp).st_mtime)
				m = n if not sub else '%s.%s' % (sub.replace('/', '.'), n)
				__import__(m)
				# print '\n[Microserver] Incremental proto:', m

	if os.path.isfile(path) and path.endswith('.py'):
		with codecs.open(path, 'r', 'utf-8') as f:
			exec str(f.read()) in {}
		proto.timestamps[path] = str(os.stat(path).st_mtime)
	elif os.path.isdir(path):
		_scanScripts('')

	for n, c in MetaEntity.Entities.iteritems():
		setattr(proto, n, c)
	for c in MetaComponent.Components.itervalues():
		setattr(proto, _componentName(c), c)

	types = []
	entities = {}
	components = {}
	for n in dir(proto):
		c = getattr(proto, n)
		if isinstance(c, type) and issubclass(c, Component):
			types.append("""
%s = type('%s', (microserver.Component, ), {
	'____virtual__' = True,
	'__module__' = '%s',%s
}
""" % (n, c.__name__, c.__module__, ''))
			components[n] = {}

	for n in dir(proto):
		c = getattr(proto, n)
		if isinstance(c, type) and issubclass(c, Entity):
			types.append("""
class %s(microserver.Entity):
	____virtual__ = True%s
""" % (n, ''.join(["""
	%s = microserver.Component(%s, '%s')""" % (k, _componentName(v.klass), v.path) for k, v in c.____components__.iteritems()])))
			entities[n] = {'Components': {k: components[_componentName(v.klass)] for k, v in c.____components__.iteritems()}}

	_compareWrite(proto_file, MICROSERVER_PROTO__ % ('\n\t'.join(['\'%s\': \'%s\',' % (p, t) for p, t in sorted(proto.timestamps.iteritems())]), ''.join(types)))

	print repr(entities).replace("'", '"')


MICROSERVER_PROTO__ = ur"""#-*- coding: utf-8 -*-
# Generated by ibelie-rpc.  DO NOT EDIT!

import microserver

timestamps = {
	%s
}
%s
"""


if __name__ == '__main__':
	import sys
	extract(*sys.argv[1:])
